### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by simrotion13** [x0rr-dan/s1c0n#1]
getting error while running the script

┌──(kali㉿kali)-[~/tools/s1c0n]
└─$ python3 sicon.py -u hackerone.com       

           [!] Error on import No module named 'nmap'
[*] nmap exist
Traceback (most recent call last):
  File "/home/kali/tools/s1c0n/sicon.py", line 51, in <module>
    check(tool)
  File "/home/kali/tools/s1c0n/sicon.py", line 29, in check
    time.sleep(0.2)
NameError: name 'time' is not defined

**Comment by bl700** [comment]
sudo apt install nmap 
Or 
pip3 install namp

to fixe the problem

**Comment by bl700** [comment]
Add in the top 

import time

**Comment by x0rr-dan** [comment]
the problem is in the nmap module which is not installed
you can install it using `pip3 install nmap` or `pip3 install python-nmap`
