### ISSUE TITLE
getting error when runing rquirement install

### ISSUE THREAD

**Issue by Cache-Bounty** [x0rr-dan/s1c0n#4]
% **pip3 install -r requirement.txt** 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Invalid requirement: "GET /performapi/api/SystemLookup?$filter=ColumnCode%20gt%20' HTTP/1.1" (from line 1 of req.txt)
Hint: It looks like a path. File 'GET /performapi/api/SystemLookup?$filter=ColumnCode%20gt%20' HTTP/1.1' does not exist.
WARNING: There was an error checking the latest version of pip.

**Comment by x0rr-dan** [comment]
I think there is a problem with your device, i mean the python.

from the error message above:
`WARNING: There was an error checking the latest version of pip.`
try upgrading your pip3 using this command
`python3 -m pip install --upgrade pip.`

**Comment by x0rr-dan** [comment]
maybe someone can give another solution than what i told?

**Comment by IgnacioPro** [comment]
> maybe someone can give another solution than what i told?

Looks more like an error from the api itself than pip.
